ignore:
  - "**/generated/**/*"
  - "**/generated/*"
  - "**/cypress/*/*.ts"

coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
        if_ci_failed: error #success, failure, error, ignore
    patch:
      default:
        enabled: no
        if_not_found: success