[[redirects]]
  from = "/you"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/whitelist"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/nftdotcom"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.prod.environment]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-FKHMGFQKR0"
  NEXT_PUBLIC_ENV = "PRODUCTION"

[context.staging.environment]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-W1SG7G6BJN"
  NEXT_PUBLIC_ENV = "STAGING"

[context.stable.environment]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-W1SG7G6BJN"
  NEXT_PUBLIC_ENV = "SANDBOX"

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"