[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn build:netlify"
publish = ".next"

[[redirects]]
  from = "/you"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/whitelist"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/nftdotcom"
  status = 200
  force = true

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"