[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn build:netlify && yarn postbuild"
publish = ".next"

[[redirects]]
  from = "/whitelist"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/nftdotcom"
  status = 200
  force = true

[[redirects]]
  from = "/you"
  to = "https://www.nft.com/app/mint-profiles"
  status = 200
  force = true

[[redirects]]
  from = "/You"
  to = "https://www.nft.com/app/mint-profiles"
  status = 200
  force = true

[[redirects]]
  from = "/YOU"
  to = "https://www.nft.com/app/mint-profiles"
  status = 200
  force = true

[[redirects]]
  from = "/YoU"
  to = "https://www.nft.com/app/mint-profiles"
  status = 200
  force = true

[[redirects]]
  from = "/YOu"
  to = "https://www.nft.com/app/mint-profiles"
  status = 200
  force = true
