[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn build:netlify"
publish = ".next"

[[redirects]]
  from = "/you"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/whitelist"
  to = "https://whitelist.nft.com"
  status = 200
  force = true

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/nftdotcom"
  status = 200
  force = true

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
  Content-Security-Policy = "default-src 'self'; script-src 'report-sample' 'self' 'unsafe-eval' https://cdn.segment.com/* https://*.facebook.net/* https://edge.fullstory.com/s/fs.js https://s3-us-west-2.amazonaws.com/jsstore/a/5N0HR7E/ge.js https://static.hotjar.com/c/hotjar-2821621.js https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtm.js/*; style-src 'report-sample' 'self' 'unsafe-inline' https://*.googleapis.com/* https://*.nft.com/* *; object-src 'none'; base-uri 'self'; connect-src 'self' https://api.coingecko.com/* https://*.alchemyapi.io/* https://*nft.com/* https://api.etherscan.io/* https://*.infura.io/* https://*.sentry.io/* https://connect.facebook.net/* https://*.hotjar.com/*; font-src 'self' https://fonts.gstatic.com/* https://nftcom-prod-assets.s3.amazonaws.com/* https://*.nft.com/*; frame-src 'self'; img-src * data: *; manifest-src 'self'; media-src *; report-uri 'none'; worker-src 'none'; "
