[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.prod.environment]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-FKHMGFQKR0"
  NEXT_PUBLIC_ENV = "PRODUCTION"

[context.staging.environment]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-W1SG7G6BJN"
  NEXT_PUBLIC_ENV = "STAGING"

[context.stable.environment]
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-W1SG7G6BJN"
  NEXT_PUBLIC_ENV = "SANDBOX"