name: Deploy NFT.com Frontend
on:
  push:

jobs:
  deploy-preview:
    if: ${{ startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') }}
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn install --frozen-lockfile --immutable
    
    - name: Deploy Site Preview
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_GH_TOKEN }}
      run: netlify deploy --build --context deploy-preview --message "${{ github.head_ref }}@${{ github.sha }}"
    
  deploy-sandbox:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_GH_TOKEN }}
        run: netlify deploy --build --prod --message "main@${{ github.sha }}"
  
  deploy-staging:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'staging') }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable
        
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_GH_TOKEN }}
        run: netlify deploy --build --prod --message "staging@${{ github.sha }}"
        
  deploy-prod:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'prod') }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable
      
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_GH_TOKEN }}
        run: netlify deploy --build --prod --message "prod@${{ github.sha }}"
